---
startDelaySeconds: 0
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["org.eclipse.jetty.server.handler:*", "org.eclipse.jetty.server:*", "pingfederate:*", "java.lang:*"]
