---
startDelaySeconds: 0
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["org.eclipse.jetty.server.handler: statisticshandler", "org.eclipse.jetty.server: connectorstatistics", "pingfederate:*", "java.lang:*"]
