kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingcommon/my-ping?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-services/p14c-bootstrap
  newTag: ${P14C_BOOTSTRAP_IMAGE_TAG}

- name: ${ECR_REGISTRY_NAME}/pingcloud-services/p14c-integration
  newTag: ${P14C_INTEGRATION_IMAGE_TAG}

- name: ${ECR_REGISTRY_NAME}/pingcloud-solutions/ansible-beluga
  newTag: ${ANSIBLE_BELUGA_IMAGE_TAG}

patches:

### imagePullPolicy patches ###

- target:
    group: apps
    version: v1
    kind: Deployment
    name: p14c-bootstrap
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: ${IMAGE_PULL_POLICY}

- target:
    group: apps
    version: v1
    kind: Deployment
    name: p14c-bom-service
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: ${IMAGE_PULL_POLICY}

- target:
    group: apps
    version: v1
    kind: Deployment
    name: p14c-oauth-service
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: ${IMAGE_PULL_POLICY}

- target:
    group: batch
    version: v1
    kind: Job
    name: pingone-configurator
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: ${IMAGE_PULL_POLICY}