workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

## Pipeline stages ##
stages:
- pre-compile
- compile
- deploy
- unit-test
- pa-was-test
- integration-test
- chaos
- cleanup

## Global environment variables ##
variables:
  DELETE_ENV_AFTER_PIPELINE: 'true'

## Pre-Compile stage ##
pre-compile:
  stage: pre-compile
  tags:
    - default-gitlab-runner
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
  script:
  - ./ci-scripts/pre-compile/verify_k8s_image_repositories.sh
  only:
    refs:
    - tags
    
## Compile stage ##
compile:
  stage: compile
  tags:
    - default-gitlab-runner
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
  script:
  - ./ci-scripts/compile/compile.sh

## Build stage ##
deploy:
  stage: deploy
  tags:
  - default-gitlab-runner
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
  script:
  - ./ci-scripts/deploy/deploy.sh
  artifacts:
    reports:
      dotenv: deploy.env

### Unit tests have moved into ping-cloud-docker (PDO-1739) ##
#
### PA-WAS stage ##
#pa-was-integration-tests:
#  stage: pa-was-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#    - ./ci-scripts/test/integration/run-integration-tests.sh pingaccess-was
#  dependencies:
#    - deploy
#
### Integration Test stage ##
#pd-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#  - ./ci-scripts/test/integration/run-integration-tests.sh pingdirectory
#  dependencies:
#    - deploy
#
#da-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#    - ./ci-scripts/test/integration/run-integration-tests.sh pingdelegator
#  dependencies:
#    - deploy
#
#pf-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#  - ./ci-scripts/test/integration/run-integration-tests.sh pingfederate
#  dependencies:
#    - deploy
#
#pa-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#    - ./ci-scripts/test/integration/run-integration-tests.sh pingaccess
#  dependencies:
#    - deploy
#
#pc-services-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#    - ./ci-scripts/test/integration/run-integration-tests.sh pingcloud-services
#  dependencies:
#    - deploy
#
#pcentral-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#    - ./ci-scripts/test/integration/run-integration-tests.sh pingcentral
#  dependencies:
#    - deploy
#
#datasync-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#    - ./ci-scripts/test/integration/run-integration-tests.sh pingdatasync
#  dependencies:
#    - deploy
#
#common-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#    - ./ci-scripts/test/integration/run-integration-tests.sh common
#  dependencies:
#    - deploy
#
#monitoring-integration-tests:
#  stage: integration-test
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#    - ./ci-scripts/test/integration/run-integration-tests.sh monitoring
#  dependencies:
#    - deploy
#
### Chaos testing stage ##
#chaos-tests:
#  stage: chaos
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#  - ./ci-scripts/test/integration/run-integration-tests.sh chaos
#  dependencies:
#    - deploy
#
### Cleanup stage ##
#cleanup:
#  stage: cleanup
#  tags:
#    - default-gitlab-runner
#  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:2.0.0
#  script:
#  - ./ci-scripts/cleanup/teardown.sh
#  dependencies:
#    - deploy
