apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ping-role
rules:
  - apiGroups:
    - ""
    resources:
    - "pods"
    - "pods/log"
    - "secrets"
    - "configmaps"
    - "namespaces"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - "persistentvolumeclaims"
    verbs:
    - delete
  - apiGroups:
    - ""
    - "apps"
    resources:
    - "statefulsets"
    - "deployments"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - "pods/exec"
    verbs:
    - create
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ping-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ping-role
subjects:
  - kind: ServiceAccount
    name: ping-serviceaccount