apiVersion: batch/v1
kind: CronJob
metadata:
  name: healthcheck-pingaccess-was
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 90
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: cluster-healthcheck-serviceaccount
          restartPolicy: OnFailure
          containers:
          - name: pingaccess-was-health
            image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-services/robot-framework:PDO-4439-pf-tests
            imagePullPolicy: Always
            securityContext:
              runAsGroup: 9999
              runAsNonRoot: true
              runAsUser: 9031
              allowPrivilegeEscalation: false
            command:
              - /bin/bash
              - -c
              - ./robot_wrapper.py --path tests/pingaccess-was --include pingAccessWas --output pingAccessWas.xml
            envFrom:
            - configMapRef:
                name: cluster-health-environment-variables