kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- files
- enrichment-resources.yaml
- enrichment-bootstrap.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: logging-bootstrap-environment-variables
  literals:
    - SERVICE_SSM_PATH_PREFIX=/pcpt/service

- name: logging-bootstrap-config
  files:
    - app_config.yaml
