apiVersion: batch/v1
kind: CronJob
metadata:
  name: healthcheck-cluster-health
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ping-serviceaccount
          restartPolicy: Never
          containers:
          - name: healthcheck-cluster-health
            image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-services/robot-framework:v1.1.0-pdo-3907-cluster-health
            imagePullPolicy: Always
            securityContext:
              runAsGroup: 9999
              runAsNonRoot: true
              runAsUser: 9031
              allowPrivilegeEscalation: false
            command:
              - /bin/bash
              - -c
              - ./robot_wrapper.sh cluster-health.xml "--include cluster-health tests/cluster-health"
            envFrom:
            - configMapRef:
                name: pingcloud-healthcheck-environment-variables
