kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: health

commonLabels:
  app: ping-cloud

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingcloud-healthcheck-environment-variables

resources:
- cluster-health.yaml
- deployment.yaml
- ingress.yaml
- namespace.yaml
- service.yaml
- serviceaccount.yaml