---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-cluster-headless
  namespace: elastic-stack-logging
$patch: delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: opensearch-sc1
provisioner: ebs.csi.aws.com
$patch: delete
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
$patch: delete