apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic-stack-logging
spec:
  type: ExternalName
  externalName: elasticsearch.${PRIMARY_DNS_ZONE}
  $patch: replace
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster-hot
  namespace: elastic-stack-logging
$patch: delete
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster-warm
  namespace: elastic-stack-logging
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-log4j-properties
  namespace: elastic-stack-logging
$patch: delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-sc1
provisioner: kubernetes.io/aws-ebs
$patch: delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-gp2
provisioner: kubernetes.io/aws-ebs
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic-stack-logging
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-stack-logging
$patch: delete
---
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-bootstrap
  namespace: elastic-stack-logging
$patch: delete
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-bootstrap
  namespace: elastic-stack-logging
$patch: delete
