# NOTE: unlike the rest of this directory, this file is managed by Ping
# The rest of this directory is a direct copy of https://github.com/CrunchyData/postgres-operator-examples
# TODO: potentially fork so not in repo??
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  # TODO: just the default PGO namespace for now
  - namespace
  - default

images:
  - name: registry.developers.crunchydata.com/crunchydata/postgres-operator
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/postgres-operator
  - name: registry.developers.crunchydata.com/crunchydata/postgres-operator-upgrade
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/postgres-operator-upgrade
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-upgrade
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres-gis
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-pgadmin4
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-pgbackrest
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-pgbouncer
  - name: registry.developers.crunchydata.com/crunchy-postgres-exporter
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchy-postgres-exporter

# Patch the CRDs such that argocd will sync them properly
patchesJson6902:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: postgresclusters.postgres-operator.crunchydata.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "Replace=true"
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: pgupgrades.postgres-operator.crunchydata.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "Replace=true"
