apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: prom-webhook
spec:
  service:
    ports:
      - port: 13000
        targetPort: 13000
  webhook:
    prom-webhook:
      port: "13000"
      endpoint: /notification
      method: POST

---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: prom-webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: trigger-slack
      eventSourceName: prom-webhook
      eventName: prom-webhook
  triggers:
    - template:
        name: trigger-slack
        slack:
          channel: general
          message: this is default message from argo-events
          slackToken:
            key: token
            name: test-secret
      parameters:
        - src:
            dependencyName: trigger-slack
            dataTemplate: |-
              *Status*: {{ (index .Input.body.alerts 0).status }}
              *Description*: {{ (index .Input.body.alerts 0).annotations.description }}
              *Summary*: {{ (index .Input.body.alerts 0).annotations.summary }}
          dest: slack.message

---
kind: Secret
apiVersion: v1
metadata:
  name: test-secret
data:
  token: eG94Yi00MTc0NjcxNTM5NzgwLTQxNzAxNjMyMjE3OTgtZHlEczBOV2ZXYlhtUk8wZndkdTdVQXVnCg==