apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: prom-webhook
spec:
  service:
    ports:
      - port: 13000
        targetPort: 13000
  webhook:
    prom-webhook:
      port: "13000"
      endpoint: /notification
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: prom-webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: prom-webhook
      eventName: prom-webhook
  triggers:
    - template:
        name: wh-trigger
        http:
          url: https://webhook.site/eeb6aaea-a691-459d-88e6-0e8e8a073b7c
          payload:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: message
          method: POST
      retryStrategy:
        steps: 3
        duration: 3s