---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      initContainers:

      - name: check-elasticsearch-availability
        image: busybox
        command: ['sh', '-c', "until nslookup elasticsearch.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for elasticsearch; sleep 2; done"]

      - name: get-kibana-config
        image: busybox
        workingDir: /scripts
        command: ["sh", '$(CONTAINER_NAME).sh']

        env:
        - name: WAIT_FOR
          value: "create-certs-and-creds"
        - name: CONTAINER_NAME
          value: "get-kibana-config"

        volumeMounts:
        - name: enrichment-shared-volume
          mountPath: /enrichment-shared-volume
          readOnly: false
        - name: enrichment-scripts
          mountPath: /scripts

      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.8.0

        env:
        - name: WAIT_FOR
          value: "elasticsearch-bootstrap"
        - name: CONTAINER_NAME
          value: "kibana"
        - name: SERVER_NAME
          value: "kibana"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "5601"
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200

        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 100m

        ports:
        - name: http
          containerPort: 5601

        volumeMounts:
          - mountPath: /enrichment-shared-volume
            name: enrichment-shared-volume
            readOnly: false
          - name: enrichment-kibana-config
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml


      volumes:
        - name: enrichment-shared-volume
          nfs:
            server: ${EFS_FILESYSTEM_ID}.efs.${REGION}.amazonaws.com
            path: /
        - name: enrichment-scripts
          configMap:
            name: enrichment-scripts
            defaultMode: 0555
        - name: enrichment-kibana-config
          configMap:
            name: enrichment-kibana-config

---
# This service exposes the Kibana http port to the cluster.
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    name: http
  selector:
    app: kibana
