---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
  labels:
    app: logstash-elastic
data:
  pipelines.yml: |
    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline/main"

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: logstash-elastic
  labels:
    app: logstash-elastic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logstash-elastic
  template:
    metadata:
      labels:
        app: logstash-elastic
    spec:
      serviceAccount: logstash-elastic
      initContainers:

      - name: check-service-availability
        image: public.ecr.aws/r2h3l6e4/pingcloud-monitoring/enrichment-bootstrap:3.14-v1.2.1
        imagePullPolicy: IfNotPresent
        command: ["sh", '$(CONTAINER_NAME).sh']

        env:
        - name: CONTAINER_NAME
          value: "check-service-availability"

        - name: CHECK_SERVICE_URL
          value: "http://elasticsearch"
        - name: CHECK_SERVICE_PORT
          value: "9200"
        - name: DESIRED_STATUS
          value: "green"

      - name: create-enrichment-cache-files
        image: public.ecr.aws/r2h3l6e4/pingcloud-monitoring/enrichment-bootstrap:3.14-v1.2.1
        
        imagePullPolicy: IfNotPresent
        workingDir: /scripts
        command: ["sh", '$(CONTAINER_NAME).sh']

        env:
        - name: CONTAINER_NAME
          value: "create-enrichment-cache-files"
        - name:  ENRICHMENT_TOR_FEED_URL
          value: "https://check.torproject.org/exit-addresses"
        - name:  ENRICHMENT_ALIEN_VAULT_FEED_URL
          value: "https://reputation.alienvault.com/reputation.generic"
        - name:  ENRICHMENT_FILEPATH
          value: "/enrichment-cache-files/"
        - name:  PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"

        volumeMounts:
        - name: enrichment-cache
          mountPath: /enrichment-cache
        - name: enrichment-cache-files
          mountPath: /enrichment-cache-files

      containers:
      - name: logstash
        image: public.ecr.aws/r2h3l6e4/pingcloud-monitoring/logstash:8.1.3-v1.1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
          - name: CONTAINER_NAME
            value: "logstash"
          - name: LS_JAVA_OPTS
            value: "-Xmx1g -Xms1g"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: LOGSTASH_ELASTICSEARCH_URL
            value: "http://elasticsearch"
          - name: LOGSTASH_ELASTICSEARCH_PORT
            value: "9200"
          - name: CONFIG_RELOAD_AUTOMATIC
            value: "true"
          - name: CONFIG_RELOAD_INTERVAL
            value: "5s"
          - name: LOG_FORMAT
            value: "json"
          - name: LOG_LEVEL
            value: "warn"
          - name: PIPELINE_BATCH_DELAY
            value: "500"
          - name: PIPELINE_BATCH_SIZE
            value: "1500"
          - name: PIPELINE_ECS_COMPATIBILITY
            value: "disabled"
          - name: XPACK_MONITORING_ENABLED
            value: "true"
          - name: PIPELINE_ORDERED
            value: "false"
          - name: QUEUE_TYPE
            value: "persisted"
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 150m
            memory: 1Gi

        ports:
          - containerPort: 9600
            name: rest
            protocol: TCP
          - containerPort: 8080
            name: http-log-input
            protocol: TCP

        volumeMounts:
        - name: logstash-pipelines
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
          readOnly: true
        - name: logstash-pipeline-main
          mountPath: /usr/share/logstash/pipeline/main
          readOnly: true
        - name: enrichment-logstash-search-templates
          mountPath: /etc/logstash/templates
          readOnly: true
        - name: enrichment-cache-files
          mountPath: /enrichment-cache-files
          readOnly: false

      # Sidecar enrichment container which updates Logstash dictionaries
      - name: enrichment-sidecar
        image: public.ecr.aws/r2h3l6e4/pingcloud-monitoring/enrichment-bootstrap:3.14-v1.2.1
        
        imagePullPolicy: IfNotPresent
        workingDir: /scripts
        command: ["sh", '$(CONTAINER_NAME).sh']

        env:
        - name: CONTAINER_NAME
          value: "enrichment-sidecar"
        - name:  ENRICHMENT_TOR_FEED_URL
          value: "https://check.torproject.org/exit-addresses"
        - name:  ENRICHMENT_ALIEN_VAULT_FEED_URL
          value: "https://reputation.alienvault.com/reputation.generic"
        - name:  ENRICHMENT_FILEPATH
          value: "/enrichment-cache-files/"
        - name:  ENRICHMENT_DELAY_SECONDS
          value: "600"
        - name:  PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"
        
        volumeMounts:
        - name: enrichment-cache-files
          mountPath: /enrichment-cache-files
          readOnly: false

      terminationGracePeriodSeconds: 30

      volumes:
      - name: logstash-pipeline-main
        configMap:
          name: logstash-pipeline-main
      - name: logstash-pipelines
        configMap:
          name: logstash-pipelines
      - name: enrichment-logstash-search-templates
        configMap:
          name: enrichment-logstash-search-templates
      - name: enrichment-cache
        configMap:
          name: enrichment-cache
      - name: enrichment-cache-files
        emptyDir: {}

      tolerations:   
      - operator: Exists

---
kind: Service
apiVersion: v1
metadata:
  name: logstash-elastic
  labels:
    app: logstash-elastic
spec:
  selector:
    app: logstash-elastic
  ports:
    - port: 9600
      name: rest
    - port: 8080
      name: http-log-input

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logstash-elastic
  labels:
    app: logstash-elastic

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logstash-elastic
  labels:
    app: logstash-elastic
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logstash-elastic
roleRef:
  kind: ClusterRole
  name: logstash-elastic
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: logstash-elastic
